### ISSUE TITLE
still need the multiNet test cases

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss-plugin#17]
Mike, I found you deleted all test cases instead of moving them to somewhere else. Actually I still need the test cases under ipss.plugin.multiNet while moving forward, as this part needs further development and testing.

**Comment by thuang** [comment]
Mike, can you fix this issue when you have time.

**Comment by ezzhou** [comment]
Will do

**Comment by ezzhou** [comment]
Tony - are you talking about the following test cases:

https://github.com/InterPSS-Project/ipss-plugin/tree/master/ipss.plugin.multiNet/src/org/ipss/multiNet/test

**Comment by thuang** [comment]
I found the test cases deleted in this commit:
https://github.com/InterPSS-Project/ipss-plugin/commit/2a0b0bbb10962dbdeec371ccf8df810b0136efc1

**Comment by interpss** [comment]
This might be a mistake. Maybe, I was trying to move the test cases to the ipss.test.plugin.core project. Please put your test cases back into the project, if they are missing.
