### ISSUE TITLE
Logger level config is not working as expected

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss-plugin#32]
@jinjingfarm 

I have set the logging level to OFF by "IpssLogger.getLogger().setLevel(Level.OFF)" But in the output, there are still some log msg at INFO level.  Is this configuration not used properly here?

![image](https://user-images.githubusercontent.com/529196/73909519-b4c41b80-4861-11ea-9b54-6a0190ad5d6e.png)

You should be able to duplicate the issue  with the following commit. 

https://github.com/InterPSS-Project/ipss-plugin/commit/658e5ff762fe2df75bb31c3ace7a13e7e2647c99

**Comment by jinjingfarm** [comment]
@thuang The issue could not be duplicated, please see the [Investiation Case](https://github.com/InterPSS-Project/ipss-plugin/blob/inv_logConfig/ipss.test.plugin.core/src/investiation/DStab_IEEE300Bus_Test.java).

**Comment by thuang** [comment]
It turned out the issue was due to mis-use of other functions.
