### ISSUE TITLE
Error with piecewiseAlgo plugin test cases

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ipss-plugin#37]
It seems the extendedPiecewiseAlgo project on github is not up to date, as I found the test cases in ipss.test.plugin.core have errors.
![image](https://user-images.githubusercontent.com/529196/93275077-c3b46a00-f770-11ea-8957-52ea07924362.png)

**Comment by jinjingfarm** [comment]
The InterPSS lib has been updated. The issue should have been resolved now.
